theme: jekyll-theme-minimal
title: ZwiftyWiki
description: Recursos útiles para disfrutar de Zwift
logo: /logo.png
show_downloads: false
google_tag_manager: GTM-MJLDWPT
plugins:
  - jekyll-relative-links
  - jekyll-target-blank
  - jemoji
relative_links:
  enabled: true
  collections: false
